 ## Desktop
choco install adobereader
choco install calibre
choco install chromium
choco install dropbox
choco install evernote
choco install filezilla
choco install firefox
choco install foobar2000
choco install foxitreader
choco install googlechrome
choco install googledrive
choco install google-chrome-x64
choco install imagemagick.app
choco install inkscape
choco install irfanview
choco install itunes
choco install keepass
choco install libreoffice
choco install pidgin
choco install putty
choco install quicktime
choco install silverlight
choco install skype
choco install spotify
choco install steam
choco install thunderbird
choco install vlc
