REM Desktop
choco install -y adobeair
choco install -y adobereader
choco install -y adobeshockwaveplayer
choco install -y audacity
choco install -y blender
choco install -y calibre
choco install -y chromium
choco install -y dropbox
choco install -y evernote
choco install -y filezilla
choco install -y firefox
choco install -y flashplayerplugin
choco install -y flashplayeractivex
choco install -y f.lux
choco install -y foobar2000
choco install -y foxitreader
choco install -y gimp
choco install -y googlechrome
choco install -y googledrive
choco install -y googleearth
choco install -y greenshot
choco install -y imagemagick.app
choco install -y inkscape
choco install -y irfanview
choco install -y itunes
choco install -y keepass
choco install -y libreoffice
choco install -y paint.net
choco install -y picasa
choco install -y pidgin
choco install -y putty
choco install -y qbittorrent
choco install -y quicktime
choco install -y safari
choco install -y silverlight
choco install -y skype
choco install -y spotify
choco install -y steam
choco install -y teamviewer
choco install -y thunderbird
choco install -y vlc
